--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: myapp
  name: myapp-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: myapp
  template: 
    metadata: 
      labels: 
        app: myapp
    spec: 
      containers: 
        - 
          image: "lukaszgolabek/task001:latest"
          name: myapp
--- 
apiVersion: v1
kind: Service
metadata: 
  name: my-service-node-port
spec: 
  ports: 
    - 
      nodePort: 30000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector: 
    app: myapp
  type: NodePort