apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: log-pod
  name: log-pod
spec:
  containers:
  - image: busybox:latest
    command: ["echo This is message from log system"]
    name: log-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
