apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exec-pod
  name: exec-pod
spec:
  containers:
  - image: alpine:latest
    command: ["/bin/sh", "-c", "while true;do echo This is message from exec system > message.txt; sleep 10000; done"]
    name: exec-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
