apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: describe-pod
  name: describe-pod
spec:
  containers:
  - image: ubuntu:groovy
    name: describe-pod
    command: ["/bin/sh", "-c", "sleep 10000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
